In [1]:

import pandas as pd

# Read the CSV file in chunks of 1000 rows
df_iter = pd.read_csv('../data/filtered.csv', chunksize=1000)

# Combine all chunks into one DataFrame
df = pd.concat(df_iter, ignore_index=True)

# Now df contains the entire dataset
print("Shape of the data:", df.shape)

Shape of the data: (357284, 21)

In [2]:
df.head(10)

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,...,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID,Narrative_Word_Count,Product_clean,Standard_Product
0,2025-06-20,credit card,General-purpose credit card or charge card,Problem with a company's investigation into an...,Was not notified of investigation status or re...,NaN,NaN,"EQUIFAX, INC.",TX,75104,...,NaN,Web,2025-06-20,In progress,Yes,NaN,14196294,0,credit card,Credit Card
1,2025-06-07,checking or savings account,Checking account,Managing an account,Problem using a debit or ATM card,NaN,NaN,WELLS FARGO & COMPANY,TX,75034,...,NaN,Referral,2025-06-09,In progress,Yes,NaN,13984551,0,checking or savings account,Savings Account
2,2025-06-07,checking or savings account,Checking account,Closing an account,Company closed your account,NaN,NaN,WELLS FARGO & COMPANY,NV,89115,...,NaN,Web,2025-06-07,In progress,Yes,NaN,13956296,0,checking or savings account,Savings Account
3,2025-06-20,credit card,General-purpose credit card or charge card,Problem with a company's investigation into an...,Was not notified of investigation status or re...,NaN,NaN,Experian Information Solutions Inc.,CA,92553,...,NaN,Web,2025-06-20,In progress,Yes,NaN,14196854,0,credit card,Credit Card
4,2025-06-20,credit card,General-purpose credit card or charge card,Problem with a company's investigation into an...,Was not notified of investigation status or re...,NaN,NaN,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",TX,77346,...,NaN,Web,2025-06-20,In progress,Yes,NaN,14196870,0,credit card,Credit Card
5,2025-06-20,credit card,General-purpose credit card or charge card,Problem with a company's investigation into an...,Was not notified of investigation status or re...,NaN,NaN,"EQUIFAX, INC.",TX,77346,...,NaN,Web,2025-06-20,In progress,Yes,NaN,14196880,0,credit card,Credit Card
6,2025-06-20,credit card,General-purpose credit card or charge card,Incorrect information on your report,Account status incorrect,NaN,NaN,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",LA,71108,...,NaN,Web,2025-06-20,In progress,Yes,NaN,14197003,0,credit card,Credit Card
7,2025-06-20,checking or savings account,Checking account,Closing an account,Funds not received from closed account,NaN,NaN,TransferWise Ltd,DE,19901,...,NaN,Web,2025-06-20,Closed with explanation,Yes,NaN,14197335,0,checking or savings account,Savings Account
8,2025-06-20,credit card,General-purpose credit card or charge card,Getting a credit card,Card opened without my consent or knowledge,NaN,NaN,"EQUIFAX, INC.",TX,75065,...,NaN,Web,2025-06-20,In progress,Yes,NaN,14197343,0,credit card,Credit Card
9,2025-06-20,credit card,General-purpose credit card or charge card,Problem with a company's investigation into an...,Was not notified of investigation status or re...,NaN,NaN,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",TX,75104,...,NaN,Web,2025-06-20,In progress,Yes,NaN,14197349,0,credit card,Credit Card

In [2]:
df.shape
# data with and with out complaints

(357284, 21)

In [7]:


# Drop rows where 'Consumer complaint narrative' is missing or empty
df = df[df['Consumer complaint narrative'].notna() & (df['Consumer complaint narrative'].str.strip() != '')]

# Confirm how many rows remain
print(f"Remaining complaints with narratives: {df.shape[0]}")

# Overwrite the same CSV file
df.to_csv("../data/filtered.csv", index=False)
print("Updated CSV saved (only complaints with narratives).")

Remaining complaints with narratives: 357284
Updated CSV saved (only complaints with narratives).

In [8]:
# complaints with narratives only 
df.shape

(357284, 21)

In [3]:

# Count complaints per product
product_counts = df['Product'].value_counts()

# Display counts
print("Number of complaints per product:\n")
print(product_counts)

Number of complaints per product:

Product
checking or savings account                                140319
credit card or prepaid card                                108667
credit card                                                 80667
payday loan, title loan, or personal loan                   17238
payday loan, title loan, personal loan, or advance loan      8896
money transfers                                              1497
Name: count, dtype: int64

In [4]:
# lowering to lower case 

# Lowercase specific columns
df['Product'] = df['Product'].str.lower()
df['Consumer complaint narrative'] = df['Consumer complaint narrative'].str.lower()

# Check the result
print(df[['Product', 'Consumer complaint narrative']].head())

# Save back to the same CSV file
df.to_csv("../data/filtered.csv", index=False)
print("Text has been lowercased and saved back to the file.")

                       Product  \
0                  credit card
1  checking or savings account
2                  credit card
3                  credit card
4                  credit card

                        Consumer complaint narrative
0  a xxxx xxxx card was opened under my name by a...
1  i made the mistake of using my wellsfargo debi...
2  i requested a case number but they wont send m...
3  i have a citi rewards cards the credit balance...
4  bi am writing to dispute the following charges...
Text has been lowercased and saved back to the file.

In [14]:
df.head(10)

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,...,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID,Narrative_Word_Count,Product_clean,Standard_Product
102,2025-06-13,credit card,Store credit card,Getting a credit card,Card opened without my consent or knowledge,a xxxx xxxx card was opened under my name by a...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",TX,78230,...,Consent provided,Web,2025-06-13,Closed with non-monetary relief,Yes,NaN,14069121,91,credit card,Credit Card
111,2025-06-13,checking or savings account,Checking account,Managing an account,Deposits and withdrawals,i made the mistake of using my wellsfargo debi...,Company has responded to the consumer and the ...,WELLS FARGO & COMPANY,ID,83815,...,Consent provided,Web,2025-06-13,Closed with explanation,Yes,NaN,14061897,109,checking or savings account,Savings Account
120,2025-06-12,credit card,General-purpose credit card or charge card,"Other features, terms, or problems",Other problem,"dear cfpb, i have a secured credit card with c...",Company has responded to the consumer and the ...,"CITIBANK, N.A.",NY,11220,...,Consent provided,Web,2025-06-13,Closed with monetary relief,Yes,NaN,14047085,156,credit card,Credit Card
126,2025-06-12,credit card,General-purpose credit card or charge card,Incorrect information on your report,Account information incorrect,i have a citi rewards cards. the credit balanc...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",IL,60067,...,Consent provided,Web,2025-06-12,Closed with explanation,Yes,NaN,14040217,233,credit card,Credit Card
141,2025-06-09,credit card,General-purpose credit card or charge card,Problem with a purchase shown on your statement,Credit card company isn't resolving a dispute ...,b'i am writing to dispute the following charge...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",TX,78413,...,Consent provided,Web,2025-06-09,Closed with monetary relief,Yes,NaN,13968411,454,credit card,Credit Card
156,2025-06-09,credit card,General-purpose credit card or charge card,Problem when making payments,Problem during payment process,"although the account had been deemed closed, i...",Company believes it acted appropriately as aut...,Atlanticus Services Corporation,NY,11212,...,Consent provided,Web,2025-06-09,Closed with monetary relief,Yes,NaN,13965746,170,credit card,Credit Card
166,2025-06-08,checking or savings account,Checking account,Managing an account,Problem accessing account,got locked out of my account because i was try...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",MI,49401,...,Consent provided,Web,2025-06-08,Closed with explanation,Yes,NaN,13960106,235,checking or savings account,Savings Account
167,2025-06-11,credit card,General-purpose credit card or charge card,Problem when making payments,Problem during payment process,i was trying to log into my account and it wou...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",TX,XXXXX,...,Consent provided,Web,2025-06-11,Closed with explanation,Yes,NaN,14025020,114,credit card,Credit Card
205,2025-06-07,credit card,Store credit card,Problem with a purchase shown on your statement,Credit card company isn't resolving a dispute ...,i received an email in xxxx from my xxxx xxxx ...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",CO,80128,...,Consent provided,Web,2025-06-07,Closed with monetary relief,Yes,NaN,13950990,190,credit card,Credit Card
227,2025-06-07,"payday loan, title loan, personal loan, or adv...",Payday loan,Problem with the payoff process at the end of ...,NaN,under idaho state law28-46-413. payday loan bu...,Company has responded to the consumer and the ...,QC HOLDINGS INC,ID,83401,...,Consent provided,Web,2025-06-07,Closed with explanation,Yes,NaN,13949860,729,"payday loan, title loan, personal loan, or adv...",Personal Loan

In [5]:

import re


# Function to clean text by removing special characters and boilerplate
def clean_text(text):
    if isinstance(text, str):
        # Remove special characters (punctuation, symbols)
        text = re.sub(r'[^\w\s]', '', text)
        
        # Remove common boilerplate phrases (case insensitive)
        text = re.sub(r'(Dear\s+[A-Za-z\s,]+|Dear\s*(Sir/Madam|Customer|[A-Za-z]+).*?)(\n|$)', '', text, flags=re.IGNORECASE)
        text = re.sub(r'I am writing to complain.*?(\n|$)', '', text, flags=re.IGNORECASE)
        text = re.sub(r'Thank you for your attention.*?(\n|$)', '', text, flags=re.IGNORECASE)
        text = re.sub(r'Please note that.*?(\n|$)', '', text, flags=re.IGNORECASE)
        text = re.sub(r'Regards,\s*.*?(\n|$)', '', text, flags=re.IGNORECASE)
        text = re.sub(r'Best regards,\s*.*?(\n|$)', '', text, flags=re.IGNORECASE)
        
        # Remove extra spaces
        text = re.sub(r'\s+', ' ', text).strip()  # Replace multiple spaces with a single one
        
    return text

# Clean the 'Consumer complaint narrative' column
df['Consumer complaint narrative'] = df['Consumer complaint narrative'].apply(clean_text)

# Optional: Check the result for the first few rows
print(df[['Product', 'Consumer complaint narrative']].head())

# Save the cleaned data back to the same CSV
df.to_csv('../data/filtered.csv', index=False)
print("Special characters and boilerplate removed. Data saved back to the file.")

                       Product  \
0                  credit card
1  checking or savings account
2                  credit card
3                  credit card
4                  credit card

                        Consumer complaint narrative
0  a xxxx xxxx card was opened under my name by a...
1  i made the mistake of using my wellsfargo debi...
2  i requested a case number but they wont send m...
3  i have a citi rewards cards the credit balance...
4  bi am writing to dispute the following charges...
Special characters and boilerplate removed. Data saved back to the file.

In [6]:
df.head(10)

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,...,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID,Narrative_Word_Count,Product_clean,Standard_Product
0,2025-06-13,credit card,Store credit card,Getting a credit card,Card opened without my consent or knowledge,a xxxx xxxx card was opened under my name by a...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",TX,78230,...,Consent provided,Web,2025-06-13,Closed with non-monetary relief,Yes,NaN,14069121,91,credit card,Credit Card
1,2025-06-13,checking or savings account,Checking account,Managing an account,Deposits and withdrawals,i made the mistake of using my wellsfargo debi...,Company has responded to the consumer and the ...,WELLS FARGO & COMPANY,ID,83815,...,Consent provided,Web,2025-06-13,Closed with explanation,Yes,NaN,14061897,109,checking or savings account,Savings Account
2,2025-06-12,credit card,General-purpose credit card or charge card,"Other features, terms, or problems",Other problem,i requested a case number but they wont send m...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",NY,11220,...,Consent provided,Web,2025-06-13,Closed with monetary relief,Yes,NaN,14047085,156,credit card,Credit Card
3,2025-06-12,credit card,General-purpose credit card or charge card,Incorrect information on your report,Account information incorrect,i have a citi rewards cards the credit balance...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",IL,60067,...,Consent provided,Web,2025-06-12,Closed with explanation,Yes,NaN,14040217,233,credit card,Credit Card
4,2025-06-09,credit card,General-purpose credit card or charge card,Problem with a purchase shown on your statement,Credit card company isn't resolving a dispute ...,bi am writing to dispute the following charges...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",TX,78413,...,Consent provided,Web,2025-06-09,Closed with monetary relief,Yes,NaN,13968411,454,credit card,Credit Card
5,2025-06-09,credit card,General-purpose credit card or charge card,Problem when making payments,Problem during payment process,although the account had been deemed closed i ...,Company believes it acted appropriately as aut...,Atlanticus Services Corporation,NY,11212,...,Consent provided,Web,2025-06-09,Closed with monetary relief,Yes,NaN,13965746,170,credit card,Credit Card
6,2025-06-08,checking or savings account,Checking account,Managing an account,Problem accessing account,got locked out of my account because i was try...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",MI,49401,...,Consent provided,Web,2025-06-08,Closed with explanation,Yes,NaN,13960106,235,checking or savings account,Savings Account
7,2025-06-11,credit card,General-purpose credit card or charge card,Problem when making payments,Problem during payment process,i was trying to log into my account and it wou...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",TX,XXXXX,...,Consent provided,Web,2025-06-11,Closed with explanation,Yes,NaN,14025020,114,credit card,Credit Card
8,2025-06-07,credit card,Store credit card,Problem with a purchase shown on your statement,Credit card company isn't resolving a dispute ...,i received an email in xxxx from my xxxx xxxx ...,Company has responded to the consumer and the ...,"CITIBANK, N.A.",CO,80128,...,Consent provided,Web,2025-06-07,Closed with monetary relief,Yes,NaN,13950990,190,credit card,Credit Card
9,2025-06-07,"payday loan, title loan, personal loan, or adv...",Payday loan,Problem with the payoff process at the end of ...,NaN,under idaho state law2846413 payday loan busin...,Company has responded to the consumer and the ...,QC HOLDINGS INC,ID,83401,...,Consent provided,Web,2025-06-07,Closed with explanation,Yes,NaN,13949860,729,"payday loan, title loan, personal loan, or adv...",Personal Loan

In [2]:

# Count missing values per column
missing = df.isnull().sum().sort_values(ascending=False)

# Optional: Show as percentage too
missing_percent = (missing / len(df) * 100).round(2)

# Combine into a single table
missing_report = pd.DataFrame({
    'Missing Values': missing,
    'Percent Missing': missing_percent
})

print("Missing values summary:\n")
print(missing_report)

Missing values summary:

                              Missing Values  Percent Missing
Consumer disputed?                    336950            94.31
Tags                                  288073            80.63
Company public response               187411            52.45
Sub-issue                              46408            12.99
Sub-product                            18873             5.28
State                                   1757             0.49
Consumer complaint narrative             396             0.11
Date received                              0             0.00
Product                                    0             0.00
Issue                                      0             0.00
Company                                    0             0.00
Consumer consent provided?                 0             0.00
ZIP code                                   0             0.00
Submitted via                              0             0.00
Date sent to company                       0             0.00
Company response to consumer               0             0.00
Timely response?                           0             0.00
Complaint ID                               0             0.00
Narrative_Word_Count                       0             0.00
Product_clean                              0             0.00
Standard_Product                           0             0.00

In [4]:
# missing value analysis 

# Drop sparse columns with low value for analysis
df.drop(columns=[
    'Consumer disputed?',      # 94% missing — not useful
    'Tags',                    # 80% missing — vague categories
    'Company public response'  # 52% missing — not needed for fairness insights
], inplace=True)

# Fill missing 'State' with "Unknown"
df['State'] = df['State'].fillna('Unknown')  # 0.49% missing

# (Optional) Fill missing 'Sub-product' and 'Sub-issue' with "Unknown" if you want to keep all rows
df['Sub-product'] = df['Sub-product'].fillna('Unknown')  # 5.28% missing
df['Sub-issue'] = df['Sub-issue'].fillna('Unknown')      # 12.99% missing

# Save the updated file back to CSV
df.to_csv('../data/filtered.csv', index=False)
print("Columns dropped and missing values filled. File updated.")

Columns dropped and missing values filled. File updated.

In [11]:

# Count missing values per column
missing = df.isnull().sum().sort_values(ascending=False)

# Optional: Show as percentage too
missing_percent = (missing / len(df) * 100).round(2)

# Combine into a single table
missing_report = pd.DataFrame({
    'Missing Values': missing,
    'Percent Missing': missing_percent
})

print("Missing values summary:\n")
# Print the missing values summary
print(missing_report)

Missing values summary:

                              Missing Values  Percent Missing
Date received                              0              0.0
Product                                    0              0.0
Sub-product                                0              0.0
Issue                                      0              0.0
Sub-issue                                  0              0.0
Consumer complaint narrative               0              0.0
Company                                    0              0.0
State                                      0              0.0
ZIP code                                   0              0.0
Consumer consent provided?                 0              0.0
Submitted via                              0              0.0
Date sent to company                       0              0.0
Company response to consumer               0              0.0
Timely response?                           0              0.0
Complaint ID                               0              0.0
Narrative_Word_Count                       0              0.0
Product_clean                              0              0.0
Standard_Product                           0              0.0

In [13]:
df.head(10)

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company,State,ZIP code,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID,Narrative_Word_Count,Product_clean,Standard_Product
0,2025-06-13,credit card,Store credit card,Getting a credit card,Card opened without my consent or knowledge,a xxxx xxxx card was opened under my name by a...,"CITIBANK, N.A.",TX,78230,Consent provided,Web,2025-06-13,Closed with non-monetary relief,Yes,14069121,91,credit card,Credit Card
1,2025-06-13,checking or savings account,Checking account,Managing an account,Deposits and withdrawals,i made the mistake of using my wellsfargo debi...,WELLS FARGO & COMPANY,ID,83815,Consent provided,Web,2025-06-13,Closed with explanation,Yes,14061897,109,checking or savings account,Savings Account
2,2025-06-12,credit card,General-purpose credit card or charge card,"Other features, terms, or problems",Other problem,i requested a case number but they wont send m...,"CITIBANK, N.A.",NY,11220,Consent provided,Web,2025-06-13,Closed with monetary relief,Yes,14047085,156,credit card,Credit Card
3,2025-06-12,credit card,General-purpose credit card or charge card,Incorrect information on your report,Account information incorrect,i have a citi rewards cards the credit balance...,"CITIBANK, N.A.",IL,60067,Consent provided,Web,2025-06-12,Closed with explanation,Yes,14040217,233,credit card,Credit Card
4,2025-06-09,credit card,General-purpose credit card or charge card,Problem with a purchase shown on your statement,Credit card company isn't resolving a dispute ...,bi am writing to dispute the following charges...,"CITIBANK, N.A.",TX,78413,Consent provided,Web,2025-06-09,Closed with monetary relief,Yes,13968411,454,credit card,Credit Card
5,2025-06-09,credit card,General-purpose credit card or charge card,Problem when making payments,Problem during payment process,although the account had been deemed closed i ...,Atlanticus Services Corporation,NY,11212,Consent provided,Web,2025-06-09,Closed with monetary relief,Yes,13965746,170,credit card,Credit Card
6,2025-06-08,checking or savings account,Checking account,Managing an account,Problem accessing account,got locked out of my account because i was try...,"CITIBANK, N.A.",MI,49401,Consent provided,Web,2025-06-08,Closed with explanation,Yes,13960106,235,checking or savings account,Savings Account
7,2025-06-11,credit card,General-purpose credit card or charge card,Problem when making payments,Problem during payment process,i was trying to log into my account and it wou...,"CITIBANK, N.A.",TX,XXXXX,Consent provided,Web,2025-06-11,Closed with explanation,Yes,14025020,114,credit card,Credit Card
8,2025-06-07,credit card,Store credit card,Problem with a purchase shown on your statement,Credit card company isn't resolving a dispute ...,i received an email in xxxx from my xxxx xxxx ...,"CITIBANK, N.A.",CO,80128,Consent provided,Web,2025-06-07,Closed with monetary relief,Yes,13950990,190,credit card,Credit Card
9,2025-06-07,"payday loan, title loan, personal loan, or adv...",Payday loan,Problem with the payoff process at the end of ...,Unknown,under idaho state law2846413 payday loan busin...,QC HOLDINGS INC,ID,83401,Consent provided,Web,2025-06-07,Closed with explanation,Yes,13949860,729,"payday loan, title loan, personal loan, or adv...",Personal Loan

In [14]:
df.shape

(356888, 18)